### ISSUE TITLE
injection not disabled for pod when `oneagent.dynatrace.com/inject: false`

### ISSUE THREAD

**Issue by eduardobr** [Dynatrace/dynatrace-operator#1054]
For a given Pod, the following annotation would disable dynatrace-operator injection (prior to 0.8.0):
```
    annotations:
      oneagent.dynatrace.com/inject: "false"
```
After upgrading to dynatrace-operator 0.8.0, this annotation has no effect and the operator side-car is injected.

Is it a bug or there's another way of disabling it per Pod now?

Thank you

**Comment by chrismuellner** [comment]
Thanks for the report, I'm able to reproduce this and we are working on a fix.

**Comment by chrismuellner** [comment]
This is actually expected behavior. We have split up the different injection features into `oneagent` and `data-ingest` and with this annotation only the `oneagent` feature is disabled.

If you want to disable the whole injection (no init container), you can add the following annotations:
```yaml
      annotations:
        oneagent.dynatrace.com/inject: "false"
        data-ingest.dynatrace.com/inject: "false"
```

We are looking into how to make this more straight forward.
