### ISSUE TITLE
DT operator reconciles secrets too frequently

### ISSUE THREAD

**Issue by ctrought** [Dynatrace/dynatrace-operator#1251]
We like to keep a close tabs on the consumers of kube-api and found the dynatrace operator is the highest consumer of the secrets api in all of our clusters. Based on the operator logs its pretty apparent it's doing a constant reconcile of the secrets in all of the namespaces. This might only be true for app only injection as we don't use the CSI driver.

```
$ oc get apirequestcount secrets.v1 -o jsonpath='{range .status.currentHour..byUser[*]}{.requestCount}{","}{..byVerb[*].verb}{","}{.username}{","}{.userAgent}{"\n"}{end}' | sort -k 2 -t, -u | column -t -s, | sort -k1 -nr | head -4
26622  create delete get list update watch  system:serviceaccount:dynatrace:dynatrace-operator                                                             dynatrace-operator/v0.0.0
9236   get list watch                       system:serviceaccount:openshift-authentication-operator:authentication-operator                                Go-http-client/2.0
8705   get list watch                       system:serviceaccount:openshift-apiserver-operator:openshift-apiserver-operator                                Go-http-client/2.0
3486   get watch                            system:serviceaccount:openshift-machine-config-operator:default                                                machine-config-operator/v0.0.0
```

The secrets being reconciled in 400+ namespaces

1. dynatrace-dynakube-config
2. dynatrace-data-ingest-endpoint

Even though the secrets haven't changed, it will run the reconcile loop as soon as the previous one completes (avg 7 requests per second). Due to the number of calls to the api (2 per namespace) it would be preferable if there were more intelligence to determine if these secrets need to be reconciled. Example:

1. Perform a global watch and filter for the DT secrets using a fieldSelector and labelSelector to reconcile changes if necessary (e.g. inadvertently deleted or modified by user). 
2. Have the webhook configured for namespaces, to be notified when new namespaces are created and trigger the reconcile there (ie. create secrets)
3. A catch-all global reconcile like the current one that runs infrequently

An even better option would be to eliminate these secrets all together, it's a lot of duplicated data but I don't know whether that is feasible for a setup with app-only injection.

Cluster Info: OpenShift 4.10.36, Kubernetes v1.23.5
Dyntrace Operator Version: 0.9.0
DynaKube:
```
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  annotations:
    feature.dynatrace.com/activegate-authtoken: "true"
    feature.dynatrace.com/automatic-injection: "false"
  name: dynakube
  namespace: dynatrace
spec:
  activeGate:
    capabilities:
    - routing
    - metrics-ingest
    - dynatrace-api
    group: lab_cluster
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1.5Gi
      requests:
        cpu: 100m
        memory: 512Mi
  apiUrl: **************
  namespaceSelector:
    matchExpressions:
    - key: dt-enable <--- 400+ namespaces labelled
      operator: Exists
  networkZone: lab.intranet
  oneAgent:
    applicationMonitoring:
      initResources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 256Mi
      useCSIDriver: false
  skipCertCheck: true
  tokens: dynakube
```
