### ISSUE TITLE
[GitOps / Flux] The DynaKube's specification tries to specify a nodeSelector conflicts with an another Dynakube's nodeSelector

### ISSUE THREAD

**Issue by agardnerIT** [Dynatrace/dynatrace-operator#1280]
I'm trying to manage the OneAgent using [FluxCD](https://fluxcd.io/). But when flux syncs, the Dynakube gives this error:

```
NAME            REVISION                          SUSPENDED       READY   MESSAGE                                                                         

flux-system     main/d237...                     False           False   DynaKube/dynatrace/otel-demo dry-run failed, reason:                            

     1 error(s) found in the Dynakube                                                

      1. The DynaKube's specification tries to specify a nodeSelector conflicts with an another Dynakube's nodeSelector,
          which is not supported.
          The conflicting Dynakube: dynakube , error: admission webhook "webhook.dynatrace.com" denied the request:          
          1 error(s) found in the Dynakube                                                
          1. The DynaKube's specification tries to specify a nodeSelector conflicts with an another
          Dynakube's nodeSelector, which is not supported. The conflicting Dynakube: dynakube
```

# Explanation

I'm not really doing anything special:

# 1. Create a namespace
Equivalent to `kubectl create ns dynatrace`:

```
apiVersion: v1
kind: Namespace
metadata:
  name: dynatrace
```

# 2. Set up Helm repo
Equivalent to `helm repo add ...`
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dynatrace
  namespace: dynatrace
spec:
  interval: 1h0m0s
  url: https://raw.githubusercontent.com/Dynatrace/dynatrace-operator/master/config/helm/repos/stable
```

# 3. Install helm release
Equivalent to `helm install -n dynatrace ...`

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dynatrace-operator
  namespace: dynatrace
spec:
  chart:
    spec:
      chart: dynatrace-operator
      sourceRef:
        kind: HelmRepository
        name: dynatrace
      version: 0.9.1
  interval: 1m00s    
```

Using [classicFullStack.yaml](https://github.com/agardnerIT/otel-demo-cdr/blob/d84d47bdebee63d7a962b11cadf7571c62a6dc50/clusters/otel-demo-cluster/apps/dynatrace/classicFullStack.yaml).

```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dynatrace-oneagent
  namespace: dynatrace
resources:
  - classicFullStack.yaml
  - helmrelease.yaml
  - helmsource.yaml
  - namespace.yaml
```
