### ISSUE TITLE
arm64 does not work

### ISSUE THREAD

**Issue by discostu105** [Dynatrace/dynatrace-operator#139]
Hi. I have a mixed architecture cluster (amd64 and arm64). On my arm64 node (raspberry pi 4, ubuntu 20.04), OneAgent does not start properly:
```
20:43:14 Started agent deployment as a container, PID 33396.
20:43:14 Downloading agent to /tmp/Dynatrace-OneAgent-Linux.sh via https://{my-env}/api/v1/deployment/installer/agent/unix/default/latest?Api-Token=***&arch=x86&flavor=default
20:43:15 Download was skipped as the agent version did not change
20:43:15 Verifying agent installer signature
20:43:20 Verification successful
20:43:20 Deploying to: /mnt/host_root
20:43:20 Starting installer...
20:43:23 Checking root privileges...
20:43:23 OK
20:43:23 Error: Cannot determine architecture or architecture not supported: <AARCH64>
```

Obviously the agent is downloaded in x86 architecture, so then it cannot start.

Also, if ActiveGate is getting scheduled on the ARM node, it fails.

```
standard_init_linux.go:219: exec user process caused: exec format error
```

AFAIK ActiveGate does not support ARM architecture. It would be nice if the operator would help and schedule it on x86 nodes only.

**Comment by discostu105** [comment]
For the record: I was able to fix the ActiveGate deployment, by adding a `nodeselector` to it:
```
  kubernetesMonitoring:
    enabled: true
    nodeSelector:
      kubernetes.io/arch: amd64
```

**Comment by baichinger** [comment]
The problem with the OneAgent can be solved by passing `ONEAGENT_INSTALLER_SCRIPT_URL` argument with the corresponding `arch` query parameter. Immutable image support for non-AMD64 architecture is currently not supported.

The issue with the ActiveGate is a bug.

**Comment by discostu105** [comment]
For the record: I was able to get OneAgent deployed on my ARM nodes, by adding another custom resource definition, where I select arm64 architecture and specify the download URL directly via `ONEAGENT_INSTALLER_SCRIPT_URL`:

```
apiVersion: dynatrace.com/v1alpha1
kind: DynaKube
metadata:
  name: dynakube-arm
  namespace: dynatrace
spec:
  apiUrl: https://<myenvironment>/api
  
  # re-use tokens
  tokens: dynakube

  classicFullStack:
    enabled: true
    nodeSelector:
      kubernetes.io/arch: arm64
    env:
      - name: ONEAGENT_INSTALLER_SCRIPT_URL
        value: https://<myenvironment>/api/v1/deployment/installer/agent/unix/default/latest?arch=arm&flavor=default&Api-Token=<PaasToken>
```
