### ISSUE TITLE
install-oneagent container breaks non-root policy

### ISSUE THREAD

**Issue by wiegandf** [Dynatrace/dynatrace-operator#1894]
**Describe the bug**
We're deploying [istio-cni](https://istio.io/latest/docs/setup/additional-setup/cni/) that comes with the following pod security context:
```yaml
securityContext:
  fsGroup: 2000
  runAsGroup: 3000
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault
```
Dynatrace injects the install-oneagent container with the following container security context:
```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsUser: 0
```

It should also have `runAsNonRoot: false` so that we don't see the following error:
```bash
message: 'container''s runAsUser breaks non-root policy (pod: "istio-cni-node-ghjgn_istio-system(c7fa6210-a40f-40d9-b838-67aae08fa039)", container: install-oneagent)'
```

**To Reproduce**
1. Create a pod with above pod and security context

**Expected behavior**
Dynatrace injection should work with runAsNonRoot pods. Maybe the injected security context could simply be customized via the helm chart.

**Additional context**
K8s: v1.24.13
Istio: 1.17.2

**Comment by luhi-DT** [comment]
Hi, what operator version are you running? We usually add the `RunAsNonRoot: true` if the base container, in that case the istio-cni also runs as nonRoot. (runAsUser != 0 and runAsGroup != 0)

**Comment by wiegandf** [comment]
We're using dynatrace operator `v0.11.2`. The base container of istio-cni runs with 
```yaml
securityContext:
  privileged: false
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
```

**Comment by luhi-DT** [comment]
Could you also attach the securityContext, that ends up on your install-oneagent container, which breaks the policy? Thanks!

**Comment by wiegandf** [comment]
It's the one I posted in the first comment
```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsUser: 0
```
