### ISSUE TITLE
Problem with 0.12.0 not creating dynatrace-dynakube-oneagent-unprivileged

### ISSUE THREAD

**Issue by Jaykul** [Dynatrace/dynatrace-operator#1940]
On a clean cluster, the dynatrace-operator is not creating the oneagent-unprivileged service account, but is still using it for the OneAgent DaemonSet, resulting in all OneAgent pods failing to start.

**To Reproduce**

1. On a new cluster, without Dynatrace or the operator (e.g. delete the dynatrace namespace)
2. Install the Dynatrace Operator v0.12.0
3. Deploy Dynakube resource
4. Check for pods in the dynatrace namespace (only the operator, activeGate, and webhooks show up).
6. Check for DaemonSet (see 0 of 3 pods)
7. Look for why. Ran `kubectl get events -n dynatrace`

Found that the state is "FailedCreate" and the following message:

> Error creating: pods "dynasl1-oneagent-" is forbidden: error looking up service account dynatrace/dynatrace-dynakube-oneagent-unprivileged: serviceaccount "dynatrace-dynakube-oneagent-unprivileged" not found

**Expected behavior**

OneAgent should run!

**Additional context**

- We're on AKS
- I installed the operator with OLM
- With v0.11.2 of the operator, and the same config, it creates _additional service accounts_, and everything starts as expected.

### v0.11.2
```
kubectl get serviceaccount -n dynatrace
NAME                                       SECRETS   AGE
default                                    0         8m
dynatrace-activegate                       0         2m35s
dynatrace-dynakube-oneagent-privileged     0         2m37s
dynatrace-dynakube-oneagent-unprivileged   0         2m35s
dynatrace-kubernetes-monitoring            0         2m34s
dynatrace-operator                         0         2m33s
dynatrace-webhook                          0         2m37s
```

### v0.12.0
```
kubectl get serviceaccount -n dynatrace
NAME                                     SECRETS   AGE
default                                  0         9m25s
dynatrace-dynakube-oneagent-privileged   0         9m19s
dynatrace-kubernetes-monitoring          0         9m18s
dynatrace-operator                       0         9m18s
dynatrace-webhook                        0         9m17s
```

My dynakube.yaml:

```yaml
apiVersion: v1
items:
- apiVersion: dynatrace.com/v1beta1
  kind: DynaKube
  metadata:
    annotations:
      feature.dynatrace.com/automatic-kubernetes-api-monitoring: "true"
      feature.dynatrace.com/automatic-kubernetes-api-monitoring-cluster-name: sl1
    creationTimestamp: "2023-07-11T22:07:17Z"
    generation: 1
    labels:
      kustomize.toolkit.fluxcd.io/name: infrastructure-dynatrace
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: dynasl1
    namespace: dynatrace
  spec:
    apiUrl: https://off#####.live.dynatrace.com/api
    tokens: dynakube
    activeGate:
      capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
      resources:
        limits:
          cpu: 1000m
          memory: 1.5Gi
        requests:
          cpu: 500m
          memory: 512Mi
    oneAgent:
      classicFullStack:
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          key: CriticalAddonsOnly
          operator: Exists
```
