### ISSUE TITLE
Missing cpu/memory request/limits from csi-init container

### ISSUE THREAD

**Issue by jasswig** [Dynatrace/dynatrace-operator#2173]
dynatrace-oneagent-csi-driver is missing cpu/memory request/limits for the cs-init init container
```
spec:
      initContainers:
      - name: csi-init
        image: docker.io/dynatrace/dynatrace-operator:v0.13.0
        imagePullPolicy: Always
        args:
        - csi-init
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: false
          runAsUser: 0
          seLinuxOptions:
            level: s0
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /data
          name: data-dir
      containers:
```
**To Reproduce**
1. Deploy the helm chart

**Expected behavior**
cpu/memory request/limits should be defined for all the containers
