### ISSUE TITLE
Dynatrace images appear to be missing from Docker, Quay, and other sources

### ISSUE THREAD

**Issue by Forcebyte** [Dynatrace/dynatrace-operator#255]
A bunch of Dynatrace infrastructure, including the oneagent-operator, appears to be missing from both docker and quay as of recent

E.g.:
```
https://hub.docker.com/r/dynatrace/dynatrace-oneagent-operator
https://hub.docker.com/r/dynatrace/dynatrace-operator
https://quay.io/repository/dynatrace/dynatrace-oneagent-operator?tab=tags
https://quay.io/repository/dynatrace/dynatrace-operator?tab=tags
```

These originally existed, and are suddenly missing with no real word of whats happened to them. My initial(?) assumption is that these are old images, but I see them still being referenced in the latest release of Dynatrace:
```
      containers:
      - args:
        - operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: docker.io/dynatrace/dynatrace-operator:v0.2.2
```

Via this release: https://github.com/Dynatrace/dynatrace-operator/releases/tag/v0.2.2 inside of the `kubernetes.yaml` file
