### ISSUE TITLE
Dynatrace Operator Is Causing a Tekton Buildah Pod to Fail on OpenShift / AWS with "unshare(CLONE_NEWUSER): Invalid argument"

### ISSUE THREAD

**Issue by MichaelFitzurka** [Dynatrace/dynatrace-operator#275]
**Steps Used to Recreate Issue:**

YAML to use in the steps below:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: buildah-bare-test
spec:
  serviceAccountName: pipeline
  restartPolicy: Never
  containers:
    - name: buildah
      image: registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
      command: ["buildah", "from", "scratch"]
      volumeMounts:
      - mountPath: /var/lib/containers
        name: varlibcontainers
  volumes:
  - emptyDir: {}
    name: varlibcontainers
```

1. Create a new Red Hat OpenShift cluster on AWS (small, 3 nodes) which starts at ver 4.7.9
2. Upgrade OCP to ver 4.7.13 (may not be necessary)
3. Upgrade OCP to ver 4.8.12 (may not be necessary)
4. Install Red Hat OpenShift Pipelines Operator ver 1.5.2 (aka Tekton) from OperatorHub
5. Create namespace thru console: buildah-test 
6. Create pod with YAML - which works
     Status: Completed
     Logs:
```
working-container
```
7. Delete pod
8. Install Dynatrace Operator ver 0.2.2
9. Try same YAML - which still works
     Status: Completed
     Logs:
```
working-container
```
10. Delete pod
11. Create DynaKube from within Dynatrace Operator
12. Try same YAML - which now fails
      Status: Error
      Logs:
```
Error during unshare(CLONE_NEWUSER): Invalid argument
level=error msg="error parsing PID \"\": strconv.Atoi: parsing \"\": invalid syntax"
level=error msg="(unable to determine exit status)"
```
13. Delete pod
14. Delete DynaKube from Dynatrace Operator
15. Delete Dynatrace Operator
16. Delete namespace central-monitoring
17. Try same YAML - which still fails
      Status: Error
      Logs:
```
Error during unshare(CLONE_NEWUSER): Invalid argument
level=error msg="error parsing PID \"\": strconv.Atoi: parsing \"\": invalid syntax"
level=error msg="(unable to determine exit status)"
```
18. Delete pod
19. Recreate all 3 OpenShift nodes; by deleting existing nodes one by one, then rolling machinesets
20. Try same YAML - which now works again
     Status: Completed
     Logs:
```
working-container
```

**Expectations:**
- Step 12 - Would expect pod to be successfully created, or at least be given a reasonable explanation for why it is now failing.
- Step 17 - Would expect Operator to clean up the removal so that pod would be created successfully again.

At least Step 19 is a viable workaround to purge the issue, but seems extreme.

See: `https://github.com/containers/buildah/issues/3455` and `https://github.com/tektoncd/operator/issues/381`
