### ISSUE TITLE
customPullSecret value not in ActiveGate StatefulSets

### ISSUE THREAD

**Issue by luigiaparicio** [Dynatrace/dynatrace-operator#293]
I'm using a private Registry to host ActiveGate container images and setting customPullSecret in Dynakube CR that contains the credentials to authenticate to that registry and pull the images.

I'm getting an ImagePullBackOff error unauthorized

Checked the Statefulset definition and is still pointing to the default pull-secret

```
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ''
      restartPolicy: Always
      serviceAccountName: dynatrace-kubernetes-monitoring
      imagePullSecrets:
        - name: dynakube-pull-secret
      schedulerName: default-scheduler
```

This is what I have in Dynakube CR:

`  customPullSecret: dynaregcred`
