### ISSUE TITLE
Dynatrace Operator not respecting namespaceSelector labels

### ISSUE THREAD

**Issue by emdneto** [Dynatrace/dynatrace-operator#3999]
**Describe the bug**
The Dynatrace Operator is currently not respecting the namespaceSelector matchLabels configuration. Despite setting specific labels to restrict the operator’s activity to certain namespaces, the Dynatrace OneAgent is being injected into all namespaces. This behavior deviates from the expected functionality, where only namespaces matching the specified labels should be affected by the operator. I'm following this guide: https://docs.dynatrace.com/docs/setup-and-configuration/setup-on-k8s/guides/operation/annotate 

**To Reproduce**
Follow this guide https://docs.dynatrace.com/docs/setup-and-configuration/setup-on-k8s/guides/operation/annotate 

**Expected behavior**
The Dynatrace Operator should only inject the OneAgent into namespaces that have the labels specified in namespaceSelector.matchLabels. Other namespaces without these labels should remain unaffected.

**Additional context**
* dynatrace-operator:1.2.2

Namespace labels:
```
ns-xyz                             Active   3d7h     dynakube.internal.dynatrace.com/instance=xyz,kubernetes.io/metadata.name=ns-xyz
```

Dynakube config:
```
  oneAgent:
    cloudNativeFullStack:
      autoUpdate: false
      codeModulesImage: public.ecr.aws/dynatrace/dynatrace-codemodules:1.293.182.20240820-160950
      image: public.ecr.aws/dynatrace/dynatrace-oneagent:1.293.182.20240820-160950
      namespaceSelector:
        matchLabels:
          dynatrace: "true"
      tolerations:
      - operator: Exists
      version: 1.293.182
```

The problem is the namespace doesn't have the label dynatrace: true and even with that pods from that namespace has oneagent injected and the initContainer: install-oneagent
