### ISSUE TITLE
arm64 issue: exec user process caused: exec format error

### ISSUE THREAD

**Issue by discostu105** [Dynatrace/dynatrace-operator#454]
I had previously got my [ARM setup to work properly](https://github.com/Dynatrace/dynatrace-operator/issues/139), but recently after upgrading to operator 0.3 and refactoring my yaml, it does not work anymore. It looks like the image itself is not ARM64 compatible. As I'm inspecting the logs, I'm getting only this line:

```
standard_init_linux.go:228: exec user process caused: exec format error
```
![image](https://user-images.githubusercontent.com/10918780/149555189-e522cce0-9513-499c-b4ea-1f1bedd4f92b.png)

Is something wrong with my config, or is this an operator bug?

``` yaml
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
spec:
  apiUrl: https://<...>/api

  networkZone: home-lab

  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
#      - metrics-ingest
    
    nodeSelector:
      kubernetes.io/arch: amd64

  oneAgent:
    classicFullStack:

      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      
      nodeSelector:
        kubernetes.io/arch: amd64

  oneAgent:
    classicFullStack:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      
      nodeSelector:
        kubernetes.io/arch: arm64

      env:
        - name: ONEAGENT_INSTALLER_SCRIPT_URL
          value: https://<...>/api/v1/deployment/installer/agent/unix/default/latest?arch=arm&flavor=default&Api-Token=<...>
```

**Comment by discostu105** [comment]
After upgrading to v0.5.0, still the same problem. I believe the problem is with the downloaded oneagent image. It seems to be not multi-arch, thus fails on ARM.

![image](https://user-images.githubusercontent.com/10918780/158758606-358fcfc7-ae8b-4889-8003-6cd7e2edfff6.png)

**Comment by discostu105** [comment]
I managed to get this working again, by using the oneagent image from docker hub. It is capable of multi-arch, while the dynatrace cluster container registry API seems to be not. My config for reference:

```
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
  annotations:
    alpha.operator.dynatrace.com/feature-automatic-kubernetes-api-monitoring: "true"
spec:
  apiUrl: https://<...>/api

  networkZone: home-lab

  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - metrics-ingest
    
    nodeSelector:
      kubernetes.io/arch: amd64

  oneAgent:
    classicFullStack:
      enabled: true

      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      
      nodeSelector:
        kubernetes.io/arch: amd64
---
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube-arm
  namespace: dynatrace
  annotations:
    alpha.operator.dynatrace.com/feature-automatic-kubernetes-api-monitoring: "true"
spec:
  apiUrl: https://<...>/api
  networkZone: home-lab
  tokens: dynakube

  oneAgent:
    classicFullStack:
      enabled: true
      image: "dynatrace/oneagent"

      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists

      nodeSelector:
        kubernetes.io/arch: arm64

      env:
      - name: ONEAGENT_INSTALLER_SCRIPT_URL
        value: https://<...>/api/v1/deployment/installer/agent/unix/default/latest?arch=arm&flavor=default&Api-Token=<...>
```
