### ISSUE TITLE
Allow annotations for webhookConfigurations using helm values file

### ISSUE THREAD

**Issue by nh-armakita** [Dynatrace/dynatrace-operator#4641]
**Is your feature request related to a problem? Please describe.**
When deploying dynatrace-operator using ArgoCD and helm to AKS, AKS will inject following namespaceSelectors to MutatingWebhookConfiguration and ValidatingWebhookConfiguration:
```
    namespaceSelector:
      matchExpressions:
        - key: control-plane
          operator: NotIn
          values:
            - 'true'
        - key: kubernetes.azure.com/managedby
          operator: NotIn
          values:
            - aks
```
When the dynatrace-operator is deployed using ArgoCD, it causes the application to always be in out-of-sync state, since the namespaceSelectors do not match with the ones in helm chart. 

**Describe the solution you'd like**
Add possibility to define annotations for webhookConfiguration to prevent AKS to inject namespaceSelectors: https://learn.microsoft.com/en-us/azure/aks/faq#can-admission-controller-webhooks-impact-kube-system-and-internal-aks-namespaces-

File: https://github.com/Dynatrace/dynatrace-operator/blob/main/config/helm/chart/default/templates/Common/webhook/mutatingwebhookconfiguration.yaml

```  
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    {{- with .Values.webhook.mutatingWebhookConfigurationAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
```

File: https://github.com/Dynatrace/dynatrace-operator/blob/main/config/helm/chart/default/templates/Common/webhook/validatingwebhookconfiguration.yaml
```  
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    {{- with .Values.webhook.validatingWebhookConfigurationAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
```

File: values.yaml
```
dynatrace-operator:
  webhook:
    mutatingWebhookConfigurationAnnotations:
      admissions.enforcer/disabled: "true"
    validatingWebhookConfigurationAnnotations:
      admissions.enforcer/disabled: "true"
```

**Describe alternatives you've considered**
Manual patching after the chart has been deployed is difficult since it's deployed using ArgoCD

**Additional context**
