### ISSUE TITLE
Can't change the Dynakube object

### ISSUE THREAD

**Issue by gecube** [Dynatrace/dynatrace-operator#4873]
Good day Sirs!

I am trying to run Dynatrace on EKS on bottlerocket distribution.

First thing was to naively apply the next manifest:

```yaml
apiVersion: dynatrace.com/v1beta3
kind: DynaKube
metadata:
  name: eks-uat
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/k8s-app-enabled: "true"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://*****.live.dynatrace.com/api
  metadataEnrichment:
    enabled: true
  oneAgent:
    cloudNativeFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
    resources:
      requests:
        cpu: 500m
        memory: 1.5Gi
      limits:
        cpu: 1000m
        memory: 1.5Gi
  logMonitoring: {}
```

Unfortunately, it was not enough as I described in https://github.com/Dynatrace/dynatrace-operator/issues/376#issuecomment-2871949362

So I decided to use this article https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/deployment/supported-technologies#aws-bottlerocket-os and this article https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/deployment/supported-technologies#aws-bottlerocket-os and change the manifest to this one (as I did not get the whole example):

```yaml
apiVersion: dynatrace.com/v1beta3
kind: DynaKube
metadata:
  name: eks-uat
  namespace: dynatrace
  annotations:
#    feature.dynatrace.com/k8s-app-enabled: "true"
    feature.dynatrace.com/automatic-kubernetes-api-monitoring: "true"
    feature.dynatrace.com/injection-readonly-volume: "true"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://*****.live.dynatrace.com/api
  metadataEnrichment:
    enabled: true
  oneAgent:
    applicationMonitoring: {}
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
    resources:
      requests:
        cpu: 500m
        memory: 1.5Gi
      limits:
        cpu: 1000m
        memory: 1.5Gi
  logMonitoring: {}
```

Now I am getting the next error:

```
DynaKube/dynatrace/eks-uat dry-run failed (Forbidden): admission webhook "[v1beta3.dynakube.webhook.dynatrace.com](http://v1beta3.dynakube.webhook.dynatrace.com/)" denied the request:
1 error(s) found in the DynaKube
1. The Dynakube's specification specifies standalone Log monitoring, but no image repository/tag is configured.
```

It clearly means that the change in the object was blocked by admission controller which is really weird as in the first YAML there was no repo/tag for logging.

Even more - from the documentation I see that the image name does not have default value, what is hm... also weird
https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters#log-monitoring-image-ref

**Comment by gecube** [comment]
It helped to explicitly set up the logging image:

```yaml
apiVersion: dynatrace.com/v1beta3
kind: DynaKube
metadata:
  name: eks-uat
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/automatic-kubernetes-api-monitoring: "true"
    feature.dynatrace.com/injection-readonly-volume: "true"
spec:
  apiUrl: https://*****.live.dynatrace.com/api
  metadataEnrichment:
    enabled: true
  oneAgent:
    applicationMonitoring: {}
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
    resources:
      requests:
        cpu: 500m
        memory: 1.5Gi
      limits:
        cpu: 1000m
        memory: 1.5Gi
  logMonitoring: {}
  templates:
    logMonitoring:
      imageRef:
        repository: dynatrace/dynatrace-logmodule
        tag: 1.313.36.20250507-184408
```
