### ISSUE TITLE
Various errors when deploying CloudNativeFullStack

### ISSUE THREAD

**Issue by Forcebyte** [Dynatrace/dynatrace-operator#606]
When utilizing the CloudNativeFullStack, we are getting the following errors when Dynatrace auto-injection occurs

### Context

At the moment, the CloudNativeFullstack configuration we have pulls the OneAgent image from an AWS-based Activegate within our tenant, and reaches out to SaaS to register clusters (screenshot for a rough idea)
![image](https://user-images.githubusercontent.com/44551053/156214334-0d248ce2-8342-4075-a970-b58025b50176.png)

Sample K8s cloudnativefullstack yaml we have atm
```
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  # Dynatrace takes the name of the cluster as the name of the kubernetes integration in portal - issue put in git to fix 
  name: myclustername
  namespace: dynatrace
  annotations:
    alpha.operator.dynatrace.com/feature-automatic-kubernetes-api-monitoring: "true"

spec:
  apiUrl: https://mydynatraceactivegate:9999/e/<upstream_saas_tenant>/api
  #
  tokens: dynakube

  trustedCAs: trustedcert

  networkZone: <saas networkzone>

  namespaceSelector:
    matchLabels:
      <namespace>: <ignore this>

  oneAgent:
    # Enable cloud-native fullstack monitoring and change its settings
    # Cannot be used in conjunction with classic fullstack monitoring, application-only monitoring or host monitoring
    cloudNativeFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists

  # Configuration for ActiveGate instances.
  activeGate:
    # Enables listed ActiveGate capabilities
    capabilities:
      - routing
      - kubernetes-monitoring
      - metrics-ingest

    group: <activegate group, ignore :)>
    customProperties:
      value: |
        [http.client]
        # Set to Services Proxy
        proxy-server=<internal proxy server>.com
        proxy-port=3128
        proxy-non-proxy-hosts = <BIG list of noproxy ips for aws and internal stuff>

```

### Error 1, K8sNodeName issues

Within the install-oneagent initContainer, for some reason there are cases where the node name isn't found, so the install-oneagent container completely breaks clusters in EKS sometimes - I presume its due to the oneagent installer not accounting for cases where the K8s api does a backoff when attempting to fetch the node name (see https://github.com/kubernetes/kubernetes/issues/54482 for what I mean, there should be backup 'node name' which is equivalent to the ip spec if not found)

```
/mnt/config/init.sh: line 35: im_nodes[${K8S_NODE_NAME}]: unbound variable
```

I think this is due to Pod Mutation code here (https://github.com/Dynatrace/dynatrace-operator/blob/ae549a3c08b1fa3a6883f5cf14e9451356be0c38/src/webhook/mutation/pod_mutator.go#L361) not properly allocating for nodeName being different 

### Error 2, 

At other times, for some reason, we're getting this error from the install-oneagent container

```
/mnt/config/init.sh: line 29: [""]="xxx": bad array subscript
```

xxx above is the dynatrace environment name for our SaaS tenant
