### ISSUE TITLE
Support for special characters in proxy password

### ISSUE THREAD

**Issue by d41k4n** [Dynatrace/dynatrace-operator#680]
We found that with 0.4.2 the operator was unable to connect to the API via proxy due to an error with parsing the proxy URL.

After some troubleshooting we believe we identified the reason to be special characters contained in the proxy password as part of the secret provided via spec.proxy.valueFrom in the DynaKube.

It seems we could work around it in some cases by passing the password URL-encoded during creation of the secret but not for all cases we tested...

We also observed cases where the operator was able to connect to the proxy successfully but not the containerized ActiveGates (we've seen 407's from the proxy in the log). Granted, this could have also be caused by a temporarily locked user caused by too many unsuccessful auth attempts but during some of our tests we had cases where the operator had no errors in its log while the AG's reported proxy issues....

We didn't get a chance to test with 0.5.0 yet but since I don't see any bugfixes mentioned in this regard I expect the same problem occurring there.

Curiously, is anybody else able to confirm this behavior on their end?

**Comment by d41k4n** [comment]
We can reliably reproduce erratic behavior using a proxy password such as "07I!?.+nV-G_Xv".

If the proxy URL secret is created containing above password in URL-encoded form (see below) then this will prevent the AG pods to connect to the API and the log will show HTTP status 407 errors (tested with capability "kubernetes-monitoring"):

```
2022-04-04 09:21:38 UTC SEVERE  [<environmentID>] [<communication>, MessageBroker] Failed to send INITIAL_COLLECTOR_SETUP message (target-type=SERVER, target-id=-1004), uri=https://sg-eu-west-1-12-34-567-890-prod9-ireland.live.dynatrace.com/communication - CommunicationException: HTTP communication failed, status code=407, reason=Proxy Authentication Required
```

Secret created with:
```
oc -n dynatrace create secret generic myproxysecret --from-literal="proxy=http://someuser:07I%21%3F.%2BnV-G_Xv%2A@myproxy:8080"
```

Dynakube snippet:
```yaml
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynatrace
  namespace: dynatrace
spec:
  ...
  activeGate:
    capabilities:
    - kubernetes-monitoring
    image: ""
    replicas: 1
  apiUrl: https://environmentid.live.dynatrace.com/api
  proxy:
    valueFrom: myproxysecret
  ...
```

If secret is created with the password in clear text then even the operator won't be able to connect to the API and showing log entries such as:
```
{"level":"info","ts":"2022-04-04T06:31:45.783Z","logger":"dtclient","msg":"could not parse proxy URL!"}
```
