### ISSUE TITLE
[Feature Request] CSI driver to support for multiple node groups

### ISSUE THREAD

**Issue by edogden-pbx** [Dynatrace/dynatrace-operator#796]
As it stands at the moment with 0.6.0 cloudNativeFullStack deploy on Kubernetes EKS 1.22 if you have multiple node groups the OneAgent will deploy on all node groups. However your OneAgent pods will fail because the CSI driver by default initiates on only one node group, my manual work around was to manually add tolerations to the CSI driver DaemonSet ([as per this question](https://github.com/Dynatrace/dynatrace-operator/issues/733)) to select all my node groups, however this is not really a sustainable solution for what is meant to work out the box.

Further information:
Deployed using helm (helmsman)
Deploy Type: cloudNativeFullStack
Release: 0.6.0
Kubernetes: 1.22.6 (EKS)
2 Node Groups

**Comment by meik99** [comment]
Which tolerations have you added to the daemonset?

**Comment by edogden-pbx** [comment]
> Which tolerations have you added to the daemonset?

In my case I have two node groups `system` and `ecom` so I've added the following along with a node-role:
``` yaml
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: eks.pbx/nodegroup-name
          operator: Equal
          value: system
        - key: eks.pbx/nodegroup-name
          operator: Equal
          value: ecom
```
