### ISSUE TITLE
Openshift Operator 0.7.0 - Namespace is required for policy/v1.PodDisruptionBudget

### ISSUE THREAD

**Issue by MKInv** [Dynatrace/dynatrace-operator#895]
With Openshift 4.8 we applied the new 0.7.0 non-csi operator and got the error: ```ValueError: Namespace is required for policy/v1.PodDisruptionBudget```

In line 6 the dynatrace namespace is missing. Adding this line manually solved the problem.
https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.7.0/openshift.yaml

```
---
# Source: dynatrace-operator/templates/Common/webhook/poddisruptionbudget-webhook.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dynatrace-webhook
  namespace: dynatrace          <------------------------
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: webhook
```
